services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      FTLCONF_webserver_api_password: '${PIHOLE_FTLCONF_WEBSERVER_API_PASSWORD}'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: '86.54.11.100;86.54.11.200'
    volumes:
      - '${DOCKER_DATA}/pihole/etc-pihole:/etc/pihole'
      - '${DOCKER_DATA}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped
networks:
  homelab:
    external: true