services:
  sonarranime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarranime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $DOCKER_DATA/sonarranime/config:/config
      - $DOCKER_MEDIA/anime:/media/anime
      - $DOCKER_DOWNLOAD/qbittorrent:/download/qbittorrent
      - $DOCKER_DOWNLOAD/sabnzbd:/download/sabnzbd
    networks:
      - homelab
    labels:
      homepage.group: Arr* Stack
      homepage.name: Sonarr Anime
      homepage.icon: sonarr.png
      homepage.href: https://sonarranime.aererus.nl/
      homepage.description: Series Automation Tool
      homepage.weight: 2
      homepage.widget.type: sonarr
      homepage.widget.url: http://sonarranime:8989
      homepage.widget.key: ${API_KEY}
    restart: unless-stopped
networks:
  homelab:
    external: true
